server:
  # 端口
  port: 8080
  # 上下文
  servlet:
    context-path: /secondHandCar

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库名称
    url: jdbc:mysql://localhost:3306/second_hand_car?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    # mysql用户名
    username: root
    # mysql密码
    password: zeng0093

# mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*xml
  configuration:
    # 开启mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true

# 分页配置
pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  # pageNum<0查询第一页 pageNum>pages查询最后一页
  reasonable: true

# 日志配置
logging:
  level:
    root: info
    com.secondhand.car.trade.system: debug
